{
  lib,
  resholve,
  fetchFromGitHub,
  bash,
  coreutils,
  gnugrep,
  gnused,
  gawk,
  findutils,
  pywal,
  sway,
  nitrogen,
  qt5,
  xfce,
  glib,
  getopt,
  curl,
  feh,
  file,
  jq,
  util-linux,
  wget,
}:
resholve.mkDerivation rec {
  pname = "stylish";
  version = "unstable-2022-12-05";

  src = fetchFromGitHub {
    owner = "thevinter";
    repo = "styli.sh";
    rev = "d595412a949c6cdc7e151ae0cf929aa1958aa7f1";
    hash = "sha256-lFnzrYnTFWe8bvK//aC1+TapWIFNsNP60Msn7D0tk/0=";
  };

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp "${src}/styli.sh" $out/bin
    chmod +x $out/bin/styli.sh
    runHook postInstall
  '';

  solutions.default = {
    scripts = [ "bin/styli.sh" ];
    interpreter = "${bash}/bin/bash";
    inputs = [
      # nitrogen # just skipping since I'm on macOS
      # sway # just skipping since I'm on macOS
      # xfce # just skipping since I'm on macOS
      coreutils
      curl
      feh
      file
      findutils
      gawk
      getopt # I guess you used util-linux for this?
      glib
      gnugrep
      gnused
      jq
      pywal
      qt5.qttools
      wget
    ];
    fake.external = [
      "greadlink"
      "swaymsg" # just skipping since I'm on macOS
      "xfconf-query" # just skipping since I'm on macOS
    ];
    fix = {
      "$READLINK" = [ "readlink" ]; # coreutils
    };
    keep = {
      # this points to ~/.cache/wal/colors.sh which is apparently
      # generated by having run pywal previously. We might be able
      # to nail this down, but I don't see a `colors.sh` in pywal's
      # output, so we'd need some extra mechanism and it probably
      # wouldn't meet user expectations?
      source = [ "$SRC" ];
      # these are too dynamic to fix w/o manually patching (invocation
      # is slowly built up statefully in an array based on args)
      "$NITROGEN_ARR" = true;
      "$FEH" = true;
    };
    execer = [
      "cannot:${wget}/bin/wget" # no obvious subexec
      "cannot:${pywal}/bin/wal" # no obvious subexec
    ];
  };

  meta = with lib; {
    homepage = "https://github.com/thevinter/styli.sh";
    description = "A shell script to manage wallpapers";
    longDescription = ''
      Styli.sh is a Bash script that aims to automate the tedious process
      of finding new wallpapers, downloading and switching them via the
      configs.
      Styli.sh can search for specific wallpapers from unsplash or download
      a random image from the specified subreddits. If you have pywal it also
      can set automatically your terminal colors.
    '';
    license = licenses.mit;
    maintainers = with maintainers; [ tchab ];
  };
}
